# Generated by Django 5.1.4 on 2025-04-29 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='last_active_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='brand',
            name='daily_spend',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='brand',
            name='last_spend_update',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='brand',
            name='monthly_spend',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.CreateModel(
            name='AdSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ad')),
            ],
        ),
        migrations.DeleteModel(
            name='BrandSpend',
        ),
    ]
