# Generated by Django 5.1.4 on 2025-04-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ad_last_active_time_brand_daily_spend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='daily_spend',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='last_spend_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='monthly_spend',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
