# Generated by Django 5.1.4 on 2025-04-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_brand_daily_spend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='last_active_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
