# Generated by Django 5.1.4 on 2025-04-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ad_last_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='daily_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='monthly_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
